# -*- coding: utf-8 -*-
"""Audio Event Tagging.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K9NuM_jmouYA0LzPiBsL1f-dPKrLsSnA

#Support Vector Machine for Automatic Speech Recognition

---
https://www.kaggle.com/anmour/svm-using-mfcc-features

https://towardsdatascience.com/support-vector-machines-explained-with-python-examples-cb65e8172c85 : example of SVM

https://github.com/HareeshBahuleyan/music-genre-classification :code
https://www.groundai.com/project/music-genre-classification-using-machine-learning-techniques/1 :theory

( https://link.springer.com/chapter/10.1007/978-3-540-71505-4_11 )
Hidden Markov Models (HMMs) are, undoubtedly, the most employed core technique for Automatic Speech Recognition (ASR). Nevertheless, we are still far from achieving high-performance ASR systems.
The SVMs are effective discriminative classifiers with several outstanding characteristics, namely: their solution is that with maximum margin; they are capable to deal with samples of a very higher dimensionality; and their convergence to the minimum of the associated cost function is guaranteed.

# Data preparation
https://mycourses.aalto.fi/pluginfile.php/1155540/mod_resource/content/2/AudioEvents-presentation.pdf

-Dataset: google audioset
- n=number of classes chosen
- script for download dataset:
  -download video from youtube
  -extract audio from the video
  -cute the audio based on the start time and the end time of the audio events

# Data preprocessing and featre extraction
-for CNN: mel frequency spectogram
-for the SVM: MFCC, deltas...
"""

import tensorflow as tf
import keras
import numpy as np 
# wow

"""#Data Preparation"""

